---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nurislamho/portfolio
    - if [ -f $DEPLOYPATH/.env ]; then cp $DEPLOYPATH/.env /tmp/.env_backup; fi
    - rm -rf $DEPLOYPATH/.next $DEPLOYPATH/public $DEPLOYPATH/server.js $DEPLOYPATH/package.json
    - /bin/cp server.js package.json $DEPLOYPATH/
    - /bin/cp -R .next $DEPLOYPATH/.next
    - /bin/cp -R public $DEPLOYPATH/public
    - if [ -f /tmp/.env_backup ]; then cp /tmp/.env_backup $DEPLOYPATH/.env && rm /tmp/.env_backup; fi
